version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      WORLD: https://github.com/FormulaCraftOne/${TRACK:-FC1-Interlagos}/releases/latest/download/world.zip
