version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: 1.7.2
      WORLD: https://github.com/FormulaCraftOne/FC1-SpaFrancorchamps/releases/latest/download/FC1.SpaFranc.zip
